### PR TITLE
add source of fitdata from devices

### PR DESCRIPTION
**Pull request by allenwyma**
We have a project that requires us to get the source of the data, so we decided to modify your plugin and contribute back.

First time working with this api and flutter plugin, appreciated if you can let me know if this is useful and/or I need to make any changes.

### CODE REVIEW

**Comment by thevishvajeet** [comment]
yes please make changes we are having difficulty while using this plugin

**Comment by allenwyma** [comment]
What’s your difficultly?

**Comment by krokyze** [comment]
Hey @HangingClowns can you please accept this https://github.com/Plangora/FitKit/pull/1 pull request so I can merge these changes?

**Comment by allenwyma** [comment]
@krokyze sorry about that, somehow missed that you submitted a PR.

**Comment by krokyze** [comment]
@thevishvajeet released in version 0.0.6 ;)

**Pull request merged**
